-- Discount Management module tables (additive; no FKs). Idempotent.
CREATE TABLE IF NOT EXISTS `discount_configuration` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tenantId` INT NOT NULL,
  `businessId` INT NULL,
  `branchId` INT NULL,
  `enableModule` TINYINT(1) NOT NULL DEFAULT 1,
  `codePrefix` VARCHAR(20) NOT NULL DEFAULT 'DISC',
  `codeLength` INT NOT NULL DEFAULT 5,
  `runningNumber` INT NOT NULL DEFAULT 1000,
  `priorityOrder` TEXT NULL,
  `combinationJson` TEXT NULL,
  `gstDefault` VARCHAR(12) NOT NULL DEFAULT 'after',
  `roundOff` TINYINT(1) NOT NULL DEFAULT 1,
  `discountAccount` VARCHAR(20) NOT NULL DEFAULT '3060',
  `promoAccount` VARCHAR(20) NOT NULL DEFAULT '4210',
  `autoApply` TINYINT(1) NOT NULL DEFAULT 1,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `discount_configuration_tenantId_businessId_branchId_key` (`tenantId`, `businessId`, `branchId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `discount_master` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tenantId` INT NOT NULL,
  `businessId` INT NULL,
  `branchId` INT NULL,
  `code` VARCHAR(40) NOT NULL,
  `name` VARCHAR(150) NOT NULL,
  `description` VARCHAR(500) NULL,
  `category` VARCHAR(40) NOT NULL DEFAULT 'Standard',
  `discountType` VARCHAR(48) NOT NULL,
  `method` VARCHAR(20) NOT NULL DEFAULT 'percentage',
  `applyLevel` VARCHAR(12) NOT NULL DEFAULT 'bill',
  `value` DECIMAL(14,2) NOT NULL DEFAULT 0,
  `maxDiscount` DECIMAL(14,2) NOT NULL DEFAULT 0,
  `minDiscount` DECIMAL(14,2) NOT NULL DEFAULT 0,
  `priority` INT NOT NULL DEFAULT 100,
  `status` VARCHAR(12) NOT NULL DEFAULT 'Draft',
  `startDate` DATETIME(3) NULL,
  `endDate` DATETIME(3) NULL,
  `startTime` VARCHAR(8) NULL,
  `endTime` VARCHAR(8) NULL,
  `minBill` DECIMAL(14,2) NOT NULL DEFAULT 0,
  `maxBill` DECIMAL(14,2) NOT NULL DEFAULT 0,
  `minQty` INT NOT NULL DEFAULT 0,
  `buyProductId` INT NULL,
  `buyQty` INT NOT NULL DEFAULT 0,
  `getProductId` INT NULL,
  `getQty` INT NOT NULL DEFAULT 0,
  `applicabilityJson` TEXT NULL,
  `eligibilityJson` TEXT NULL,
  `validityJson` TEXT NULL,
  `combinationJson` TEXT NULL,
  `approvalJson` TEXT NULL,
  `discountAccount` VARCHAR(20) NULL,
  `gstTiming` VARCHAR(12) NOT NULL DEFAULT 'after',
  `reduceTaxable` TINYINT(1) NOT NULL DEFAULT 1,
  `combinable` TINYINT(1) NOT NULL DEFAULT 0,
  `requiresApproval` TINYINT(1) NOT NULL DEFAULT 0,
  `campaignId` INT NULL,
  `usageCount` INT NOT NULL DEFAULT 0,
  `totalGiven` DECIMAL(16,2) NOT NULL DEFAULT 0,
  `createdBy` INT NULL,
  `createdByName` VARCHAR(120) NULL,
  `updatedBy` INT NULL,
  `approvedBy` INT NULL,
  `approvedByName` VARCHAR(120) NULL,
  `approvedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `discount_master_tenantId_code_key` (`tenantId`, `code`),
  KEY `discount_master_tenantId_status_idx` (`tenantId`, `status`),
  KEY `discount_master_tenantId_discountType_idx` (`tenantId`, `discountType`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `discount_usage` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tenantId` INT NOT NULL,
  `businessId` INT NULL,
  `branchId` INT NULL,
  `discountId` INT NOT NULL,
  `discountCode` VARCHAR(40) NOT NULL,
  `discountName` VARCHAR(150) NOT NULL,
  `saleId` INT NULL,
  `invoiceNo` VARCHAR(40) NULL,
  `customerId` INT NULL,
  `customerName` VARCHAR(200) NULL,
  `billAmount` DECIMAL(14,2) NOT NULL DEFAULT 0,
  `discountAmount` DECIMAL(14,2) NOT NULL DEFAULT 0,
  `channel` VARCHAR(20) NULL,
  `usedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `discount_usage_tenantId_discountId_idx` (`tenantId`, `discountId`),
  KEY `discount_usage_tenantId_usedAt_idx` (`tenantId`, `usedAt`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `discount_audit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tenantId` INT NOT NULL,
  `businessId` INT NULL,
  `entityType` VARCHAR(40) NOT NULL,
  `entityId` INT NULL,
  `action` VARCHAR(60) NOT NULL,
  `byUser` INT NULL,
  `byName` VARCHAR(120) NULL,
  `note` VARCHAR(400) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `discount_audit_tenantId_entityType_entityId_idx` (`tenantId`, `entityType`, `entityId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `discount_campaign` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tenantId` INT NOT NULL,
  `businessId` INT NULL,
  `branchId` INT NULL,
  `code` VARCHAR(40) NOT NULL,
  `name` VARCHAR(150) NOT NULL,
  `campaignType` VARCHAR(40) NOT NULL DEFAULT 'Promotional',
  `startDate` DATETIME(3) NULL,
  `endDate` DATETIME(3) NULL,
  `budget` DECIMAL(16,2) NOT NULL DEFAULT 0,
  `spend` DECIMAL(16,2) NOT NULL DEFAULT 0,
  `status` VARCHAR(12) NOT NULL DEFAULT 'Draft',
  `mappingJson` TEXT NULL,
  `createdBy` INT NULL,
  `createdByName` VARCHAR(120) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `discount_campaign_tenantId_code_key` (`tenantId`, `code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
