-- GST Compliance & Statutory Management (Phase 1)
-- 9 compliance artifact tables. All figures READ from existing transaction
-- tables; these only persist verification / reconciliation / return artifacts.

-- CreateTable: gst_return_master
CREATE TABLE `gst_return_master` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `tenantId` INTEGER NOT NULL,
  `businessId` INTEGER NULL,
  `branchId` INTEGER NULL,
  `returnType` VARCHAR(12) NOT NULL,
  `period` VARCHAR(7) NOT NULL,
  `fromDate` VARCHAR(20) NOT NULL,
  `toDate` VARCHAR(20) NOT NULL,
  `gstin` VARCHAR(20) NULL,
  `legalName` VARCHAR(200) NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'Draft',
  `taxableValue` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `cgst` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `sgst` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `igst` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `cess` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `outputTax` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `itcTotal` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `netLiability` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `totals` LONGTEXT NULL,
  `jsonVersion` INTEGER NOT NULL DEFAULT 0,
  `remarks` VARCHAR(500) NULL,
  `preparedBy` INTEGER NULL,
  `preparedByName` VARCHAR(200) NULL,
  `preparedAt` DATETIME(3) NULL,
  `verifiedBy` INTEGER NULL,
  `verifiedByName` VARCHAR(200) NULL,
  `verifiedAt` DATETIME(3) NULL,
  `approvedBy` INTEGER NULL,
  `approvedByName` VARCHAR(200) NULL,
  `approvedAt` DATETIME(3) NULL,
  `createdBy` INTEGER NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  INDEX `gst_return_master_tenantId_returnType_period_idx`(`tenantId`, `returnType`, `period`),
  INDEX `gst_return_master_tenantId_status_idx`(`tenantId`, `status`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable: gst_return_items
CREATE TABLE `gst_return_items` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `tenantId` INTEGER NOT NULL,
  `returnId` INTEGER NOT NULL,
  `section` VARCHAR(12) NOT NULL,
  `refType` VARCHAR(20) NULL,
  `refId` INTEGER NULL,
  `invoiceNo` VARCHAR(40) NULL,
  `invoiceDate` VARCHAR(20) NULL,
  `partyGstin` VARCHAR(20) NULL,
  `partyName` VARCHAR(200) NULL,
  `placeOfSupply` VARCHAR(80) NULL,
  `hsn` VARCHAR(20) NULL,
  `description` VARCHAR(250) NULL,
  `uom` VARCHAR(40) NULL,
  `qty` DECIMAL(18,3) NOT NULL DEFAULT 0,
  `rate` DECIMAL(9,2) NOT NULL DEFAULT 0,
  `taxableValue` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `cgst` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `sgst` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `igst` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `cess` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `total` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `meta` TEXT NULL,
  INDEX `gst_return_items_returnId_idx`(`returnId`),
  INDEX `gst_return_items_returnId_section_idx`(`returnId`, `section`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `gst_return_items` ADD CONSTRAINT `gst_return_items_returnId_fkey`
  FOREIGN KEY (`returnId`) REFERENCES `gst_return_master`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- CreateTable: gst_gstr2b_import
CREATE TABLE `gst_gstr2b_import` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `tenantId` INTEGER NOT NULL,
  `businessId` INTEGER NULL,
  `branchId` INTEGER NULL,
  `importBatch` VARCHAR(40) NOT NULL,
  `period` VARCHAR(7) NOT NULL,
  `source` VARCHAR(10) NOT NULL DEFAULT 'JSON',
  `fileName` VARCHAR(200) NULL,
  `supplierGstin` VARCHAR(20) NULL,
  `supplierName` VARCHAR(200) NULL,
  `invoiceNo` VARCHAR(40) NULL,
  `invoiceDate` VARCHAR(20) NULL,
  `invoiceValue` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `taxableValue` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `cgst` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `sgst` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `igst` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `cess` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `gstAmount` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `eligibleItc` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `itcStatus` VARCHAR(20) NOT NULL DEFAULT 'Eligible',
  `matchStatus` VARCHAR(20) NOT NULL DEFAULT 'Pending',
  `importedBy` INTEGER NULL,
  `importedByName` VARCHAR(200) NULL,
  `importedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX `gst_gstr2b_import_tenantId_period_idx`(`tenantId`, `period`),
  INDEX `gst_gstr2b_import_importBatch_idx`(`importBatch`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable: gst_reconciliation
CREATE TABLE `gst_reconciliation` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `tenantId` INTEGER NOT NULL,
  `businessId` INTEGER NULL,
  `branchId` INTEGER NULL,
  `period` VARCHAR(7) NOT NULL,
  `supplierGstin` VARCHAR(20) NULL,
  `supplierName` VARCHAR(200) NULL,
  `invoiceNo` VARCHAR(40) NULL,
  `invoiceDate` VARCHAR(20) NULL,
  `erpInvoiceId` INTEGER NULL,
  `portalRowId` INTEGER NULL,
  `erpTaxable` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `erpGst` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `portalTaxable` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `portalGst` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `taxDifference` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `gstDifference` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `status` VARCHAR(24) NOT NULL DEFAULT 'Pending',
  `issue` VARCHAR(300) NULL,
  `action` VARCHAR(12) NOT NULL DEFAULT 'Pending',
  `resolvedBy` INTEGER NULL,
  `resolvedByName` VARCHAR(200) NULL,
  `resolvedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  INDEX `gst_reconciliation_tenantId_period_idx`(`tenantId`, `period`),
  INDEX `gst_reconciliation_tenantId_status_idx`(`tenantId`, `status`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable: gst_itc_register
CREATE TABLE `gst_itc_register` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `tenantId` INTEGER NOT NULL,
  `businessId` INTEGER NULL,
  `branchId` INTEGER NULL,
  `period` VARCHAR(7) NOT NULL,
  `purchaseInvoiceId` INTEGER NULL,
  `supplierGstin` VARCHAR(20) NULL,
  `supplierName` VARCHAR(200) NULL,
  `invoiceNo` VARCHAR(40) NULL,
  `invoiceDate` VARCHAR(20) NULL,
  `purchaseType` VARCHAR(20) NOT NULL DEFAULT 'Inventory',
  `gstAmount` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `eligibleAmount` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `ineligibleAmount` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `blockedAmount` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `claimedAmount` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `pendingAmount` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `reverseCharge` BOOLEAN NOT NULL DEFAULT false,
  `itcStatus` VARCHAR(20) NOT NULL DEFAULT 'Eligible',
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  INDEX `gst_itc_register_tenantId_period_idx`(`tenantId`, `period`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable: gst_json_export
CREATE TABLE `gst_json_export` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `tenantId` INTEGER NOT NULL,
  `businessId` INTEGER NULL,
  `branchId` INTEGER NULL,
  `returnId` INTEGER NULL,
  `returnType` VARCHAR(12) NOT NULL,
  `period` VARCHAR(7) NOT NULL,
  `gstin` VARCHAR(20) NULL,
  `version` INTEGER NOT NULL DEFAULT 1,
  `fileName` VARCHAR(200) NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `validationStatus` VARCHAR(12) NOT NULL DEFAULT 'Valid',
  `validationNotes` TEXT NULL,
  `generatedBy` INTEGER NULL,
  `generatedByName` VARCHAR(200) NULL,
  `generatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `downloadCount` INTEGER NOT NULL DEFAULT 0,
  `lastDownloadAt` DATETIME(3) NULL,
  INDEX `gst_json_export_tenantId_period_idx`(`tenantId`, `period`),
  INDEX `gst_json_export_returnId_idx`(`returnId`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `gst_json_export` ADD CONSTRAINT `gst_json_export_returnId_fkey`
  FOREIGN KEY (`returnId`) REFERENCES `gst_return_master`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- CreateTable: gst_filing_history
CREATE TABLE `gst_filing_history` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `tenantId` INTEGER NOT NULL,
  `businessId` INTEGER NULL,
  `branchId` INTEGER NULL,
  `returnId` INTEGER NULL,
  `returnType` VARCHAR(12) NOT NULL,
  `period` VARCHAR(7) NOT NULL,
  `gstin` VARCHAR(20) NULL,
  `arn` VARCHAR(40) NULL,
  `filingDate` VARCHAR(20) NULL,
  `jsonVersion` INTEGER NOT NULL DEFAULT 0,
  `jsonExportId` INTEGER NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'Filed',
  `remarks` VARCHAR(500) NULL,
  `filedBy` INTEGER NULL,
  `filedByName` VARCHAR(200) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX `gst_filing_history_tenantId_period_idx`(`tenantId`, `period`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable: gst_period_closing
CREATE TABLE `gst_period_closing` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `tenantId` INTEGER NOT NULL,
  `businessId` INTEGER NULL,
  `branchId` INTEGER NULL,
  `period` VARCHAR(7) NOT NULL,
  `fromDate` VARCHAR(20) NOT NULL,
  `toDate` VARCHAR(20) NOT NULL,
  `filingStatus` VARCHAR(20) NOT NULL DEFAULT 'Pending',
  `closingStatus` VARCHAR(12) NOT NULL DEFAULT 'Open',
  `lockedBy` INTEGER NULL,
  `lockedByName` VARCHAR(200) NULL,
  `lockedAt` DATETIME(3) NULL,
  `reopenedBy` INTEGER NULL,
  `reopenedByName` VARCHAR(200) NULL,
  `reopenedAt` DATETIME(3) NULL,
  `reopenReason` VARCHAR(300) NULL,
  `remarks` VARCHAR(300) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  INDEX `gst_period_closing_tenantId_period_idx`(`tenantId`, `period`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable: gst_validation_log
CREATE TABLE `gst_validation_log` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `tenantId` INTEGER NOT NULL,
  `businessId` INTEGER NULL,
  `branchId` INTEGER NULL,
  `period` VARCHAR(7) NOT NULL,
  `runBatch` VARCHAR(40) NOT NULL,
  `sourceType` VARCHAR(24) NOT NULL,
  `sourceId` INTEGER NULL,
  `docNo` VARCHAR(40) NULL,
  `docDate` VARCHAR(20) NULL,
  `partyName` VARCHAR(200) NULL,
  `checkCode` VARCHAR(40) NOT NULL,
  `severity` VARCHAR(12) NOT NULL,
  `message` VARCHAR(400) NOT NULL,
  `status` VARCHAR(12) NOT NULL DEFAULT 'Open',
  `resolvedBy` INTEGER NULL,
  `resolvedByName` VARCHAR(200) NULL,
  `resolvedAt` DATETIME(3) NULL,
  `resolutionNote` VARCHAR(300) NULL,
  `runBy` INTEGER NULL,
  `runByName` VARCHAR(200) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX `gst_validation_log_tenantId_period_idx`(`tenantId`, `period`),
  INDEX `gst_validation_log_runBatch_idx`(`runBatch`),
  INDEX `gst_validation_log_tenantId_status_idx`(`tenantId`, `status`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
