-- Sales Cancellation (full-invoice void) + running counter.

ALTER TABLE `sales_settings` ADD COLUMN `seqCancellation` INTEGER NOT NULL DEFAULT 0;

CREATE TABLE `sales_cancellations` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `tenantId` INTEGER NOT NULL,
  `businessId` INTEGER NULL,
  `branchId` INTEGER NULL,
  `cancellationNo` VARCHAR(40) NOT NULL,
  `cancellationDate` VARCHAR(20) NOT NULL,
  `saleId` INTEGER NOT NULL,
  `invoiceNo` VARCHAR(40) NULL,
  `channel` VARCHAR(10) NULL,
  `warehouse` VARCHAR(120) NULL,
  `customerId` INTEGER NULL,
  `customerName` VARCHAR(200) NULL,
  `customerPhone` VARCHAR(20) NULL,
  `invoiceAmount` DECIMAL(18, 2) NOT NULL DEFAULT 0,
  `refundAmount` DECIMAL(18, 2) NOT NULL DEFAULT 0,
  `refundMethod` VARCHAR(20) NULL,
  `paymentMode` VARCHAR(20) NULL,
  `reason` VARCHAR(160) NULL,
  `remarks` VARCHAR(400) NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'Draft',
  `approvedBy` INTEGER NULL,
  `approvedAt` DATETIME(3) NULL,
  `approvalNote` VARCHAR(300) NULL,
  `inventoryReversed` BOOLEAN NOT NULL DEFAULT false,
  `paymentReversed` BOOLEAN NOT NULL DEFAULT false,
  `accountingReversed` BOOLEAN NOT NULL DEFAULT false,
  `customerLedgerReversed` BOOLEAN NOT NULL DEFAULT false,
  `loyaltyReversed` BOOLEAN NOT NULL DEFAULT false,
  `journalRef` VARCHAR(40) NULL,
  `itemCount` INTEGER NOT NULL DEFAULT 0,
  `createdBy` INTEGER NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `terminalId` INTEGER NULL,
  `terminalSessionId` INTEGER NULL,
  `shiftSessionId` INTEGER NULL,
  `cashierUserId` INTEGER NULL,
  `deviceId` VARCHAR(80) NULL,
  `transactionSource` VARCHAR(20) NULL,
  `dayOpeningId` INTEGER NULL,
  `dayClosingId` INTEGER NULL,
  UNIQUE INDEX `sales_cancellations_tenantId_cancellationNo_key`(`tenantId`, `cancellationNo`),
  INDEX `sales_cancellations_tenantId_status_idx`(`tenantId`, `status`),
  INDEX `sales_cancellations_tenantId_cancellationDate_idx`(`tenantId`, `cancellationDate`),
  INDEX `sales_cancellations_saleId_idx`(`saleId`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `sales_cancellation_items` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `salesCancellationId` INTEGER NOT NULL,
  `saleLineId` INTEGER NULL,
  `productId` INTEGER NULL,
  `productName` VARCHAR(250) NOT NULL,
  `sku` VARCHAR(60) NULL,
  `hsn` VARCHAR(20) NULL,
  `qty` DECIMAL(18, 3) NOT NULL,
  `rate` DECIMAL(18, 2) NOT NULL DEFAULT 0,
  `taxAmount` DECIMAL(18, 2) NOT NULL DEFAULT 0,
  `value` DECIMAL(18, 2) NOT NULL DEFAULT 0,
  `cost` DECIMAL(18, 2) NOT NULL DEFAULT 0,
  `batchNo` VARCHAR(80) NULL,
  `mfgDate` VARCHAR(20) NULL,
  `expiryDate` VARCHAR(20) NULL,
  `serialNos` VARCHAR(500) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX `sales_cancellation_items_salesCancellationId_idx`(`salesCancellationId`),
  INDEX `sales_cancellation_items_productId_idx`(`productId`),
  PRIMARY KEY (`id`),
  CONSTRAINT `sales_cancellation_items_salesCancellationId_fkey` FOREIGN KEY (`salesCancellationId`) REFERENCES `sales_cancellations`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `sales_cancellation_payments` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `salesCancellationId` INTEGER NOT NULL,
  `mode` VARCHAR(20) NOT NULL,
  `amount` DECIMAL(18, 2) NOT NULL DEFAULT 0,
  `reference` VARCHAR(120) NULL,
  `refundStatus` VARCHAR(20) NOT NULL DEFAULT 'Completed',
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX `sales_cancellation_payments_salesCancellationId_idx`(`salesCancellationId`),
  PRIMARY KEY (`id`),
  CONSTRAINT `sales_cancellation_payments_salesCancellationId_fkey` FOREIGN KEY (`salesCancellationId`) REFERENCES `sales_cancellations`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
