-- Purchase Return (unified) + Asset Register.

-- Purchase Return header
CREATE TABLE `purchase_returns` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `tenantId` INTEGER NOT NULL,
  `businessId` INTEGER NULL,
  `branchId` INTEGER NULL,
  `returnNo` VARCHAR(40) NOT NULL,
  `returnDate` VARCHAR(20) NOT NULL,
  `purchaseInvoiceId` INTEGER NOT NULL,
  `invoiceNo` VARCHAR(40) NULL,
  `grnId` INTEGER NULL,
  `grnNo` VARCHAR(40) NULL,
  `poNo` VARCHAR(60) NULL,
  `purchaseType` VARCHAR(20) NOT NULL DEFAULT 'Inventory',
  `supplierId` INTEGER NULL,
  `supplier` VARCHAR(200) NULL,
  `supplierGstin` VARCHAR(20) NULL,
  `warehouse` VARCHAR(120) NULL,
  `reason` VARCHAR(120) NULL,
  `remarks` VARCHAR(300) NULL,
  `taxableAmount` DECIMAL(18, 2) NOT NULL DEFAULT 0,
  `taxAmount` DECIMAL(18, 2) NOT NULL DEFAULT 0,
  `roundOff` DECIMAL(9, 2) NOT NULL DEFAULT 0,
  `returnAmount` DECIMAL(18, 2) NOT NULL DEFAULT 0,
  `status` VARCHAR(20) NOT NULL DEFAULT 'Draft',
  `approvedBy` INTEGER NULL,
  `approvedAt` DATETIME(3) NULL,
  `approvalNote` VARCHAR(300) NULL,
  `inventoryUpdated` BOOLEAN NOT NULL DEFAULT false,
  `supplierOutstandingUpdated` BOOLEAN NOT NULL DEFAULT false,
  `accountingPosted` BOOLEAN NOT NULL DEFAULT false,
  `journalRef` VARCHAR(40) NULL,
  `itemCount` INTEGER NOT NULL DEFAULT 0,
  `createdBy` INTEGER NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `terminalId` INTEGER NULL,
  `terminalSessionId` INTEGER NULL,
  `shiftSessionId` INTEGER NULL,
  `cashierUserId` INTEGER NULL,
  `deviceId` VARCHAR(80) NULL,
  `transactionSource` VARCHAR(20) NULL,
  `dayOpeningId` INTEGER NULL,
  `dayClosingId` INTEGER NULL,
  UNIQUE INDEX `purchase_returns_tenantId_returnNo_key`(`tenantId`, `returnNo`),
  INDEX `purchase_returns_tenantId_status_idx`(`tenantId`, `status`),
  INDEX `purchase_returns_tenantId_returnDate_idx`(`tenantId`, `returnDate`),
  INDEX `purchase_returns_purchaseInvoiceId_idx`(`purchaseInvoiceId`),
  INDEX `purchase_returns_grnId_idx`(`grnId`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Purchase Return line
CREATE TABLE `purchase_return_items` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `purchaseReturnId` INTEGER NOT NULL,
  `piItemId` INTEGER NULL,
  `grnLineId` INTEGER NULL,
  `productId` INTEGER NULL,
  `productName` VARCHAR(250) NOT NULL,
  `sku` VARCHAR(60) NULL,
  `hsn` VARCHAR(20) NULL,
  `batchNo` VARCHAR(80) NULL,
  `mfgDate` VARCHAR(20) NULL,
  `expiryDate` VARCHAR(20) NULL,
  `assetId` INTEGER NULL,
  `invoicedQty` DECIMAL(18, 3) NOT NULL DEFAULT 0,
  `returnedQty` DECIMAL(18, 3) NOT NULL DEFAULT 0,
  `returnQty` DECIMAL(18, 3) NOT NULL,
  `rate` DECIMAL(18, 2) NOT NULL,
  `taxPct` DECIMAL(9, 2) NULL,
  `taxAmount` DECIMAL(18, 2) NOT NULL DEFAULT 0,
  `discAmount` DECIMAL(18, 2) NOT NULL DEFAULT 0,
  `returnValue` DECIMAL(18, 2) NOT NULL DEFAULT 0,
  `reason` VARCHAR(120) NULL,
  `remarks` VARCHAR(300) NULL,
  `inventoryHandling` VARCHAR(20) NOT NULL DEFAULT 'vendor',
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX `purchase_return_items_purchaseReturnId_idx`(`purchaseReturnId`),
  INDEX `purchase_return_items_productId_idx`(`productId`),
  PRIMARY KEY (`id`),
  CONSTRAINT `purchase_return_items_purchaseReturnId_fkey` FOREIGN KEY (`purchaseReturnId`) REFERENCES `purchase_returns`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Returned serial / unique-QR pieces
CREATE TABLE `purchase_return_qrs` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `tenantId` INTEGER NOT NULL,
  `purchaseReturnItemId` INTEGER NOT NULL,
  `qrCodeMappingId` INTEGER NOT NULL,
  `code` VARCHAR(80) NOT NULL,
  `serialNo` VARCHAR(120) NULL,
  `mode` VARCHAR(10) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX `purchase_return_qrs_tenantId_code_idx`(`tenantId`, `code`),
  INDEX `purchase_return_qrs_purchaseReturnItemId_idx`(`purchaseReturnItemId`),
  PRIMARY KEY (`id`),
  CONSTRAINT `purchase_return_qrs_purchaseReturnItemId_fkey` FOREIGN KEY (`purchaseReturnItemId`) REFERENCES `purchase_return_items`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Purchase Return attachments
CREATE TABLE `purchase_return_attachments` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `purchaseReturnId` INTEGER NOT NULL,
  `docType` VARCHAR(20) NOT NULL DEFAULT 'supporting',
  `fileName` VARCHAR(200) NOT NULL,
  `fileUrl` LONGTEXT NOT NULL,
  `fileType` VARCHAR(80) NULL,
  `size` INTEGER NOT NULL DEFAULT 0,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX `purchase_return_attachments_purchaseReturnId_idx`(`purchaseReturnId`),
  PRIMARY KEY (`id`),
  CONSTRAINT `purchase_return_attachments_purchaseReturnId_fkey` FOREIGN KEY (`purchaseReturnId`) REFERENCES `purchase_returns`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Asset Register
CREATE TABLE `fixed_assets` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `tenantId` INTEGER NOT NULL,
  `businessId` INTEGER NULL,
  `branchId` INTEGER NULL,
  `assetNo` VARCHAR(40) NOT NULL,
  `name` VARCHAR(250) NOT NULL,
  `category` VARCHAR(120) NULL,
  `purchaseInvoiceId` INTEGER NULL,
  `purchaseInvoiceNo` VARCHAR(40) NULL,
  `supplierId` INTEGER NULL,
  `supplier` VARCHAR(200) NULL,
  `purchaseDate` VARCHAR(20) NULL,
  `qty` DECIMAL(18, 3) NOT NULL DEFAULT 1,
  `unitValue` DECIMAL(18, 2) NOT NULL DEFAULT 0,
  `totalValue` DECIMAL(18, 2) NOT NULL DEFAULT 0,
  `location` VARCHAR(120) NULL,
  `serialNo` VARCHAR(120) NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'Active',
  `returnedAt` DATETIME(3) NULL,
  `returnRef` VARCHAR(40) NULL,
  `notes` VARCHAR(300) NULL,
  `createdBy` INTEGER NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `fixed_assets_tenantId_assetNo_key`(`tenantId`, `assetNo`),
  INDEX `fixed_assets_tenantId_status_idx`(`tenantId`, `status`),
  INDEX `fixed_assets_purchaseInvoiceId_idx`(`purchaseInvoiceId`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
