/*
  Warnings:

  - You are about to drop the column `adminContact` on the `company_setups` table. All the data in the column will be lost.
  - You are about to drop the column `flags` on the `company_setups` table. All the data in the column will be lost.
  - You are about to drop the column `primaryContact` on the `company_setups` table. All the data in the column will be lost.
  - You are about to drop the column `secondaryContact` on the `company_setups` table. All the data in the column will be lost.
  - You are about to drop the column `toggles` on the `company_setups` table. All the data in the column will be lost.
  - You are about to drop the column `workingDays` on the `company_setups` table. All the data in the column will be lost.

*/
-- AlterTable
ALTER TABLE `company_setups` DROP COLUMN `adminContact`,
    DROP COLUMN `flags`,
    DROP COLUMN `primaryContact`,
    DROP COLUMN `secondaryContact`,
    DROP COLUMN `toggles`,
    DROP COLUMN `workingDays`,
    ADD COLUMN `adminEmail` VARCHAR(150) NULL,
    ADD COLUMN `adminMobile` VARCHAR(30) NULL,
    ADD COLUMN `adminName` VARCHAR(150) NULL,
    ADD COLUMN `adminUsername` VARCHAR(60) NULL,
    ADD COLUMN `gstEinvoice` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `gstEway` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `hwBarcode` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `hwBiometric` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `hwDisplay` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `hwDrawer` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `hwQr` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `hwScale` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `hwThermal` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `impBalances` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `impCustomers` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `impProducts` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `impStock` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `impSuppliers` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `modAccounting` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `modAi` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `modChit` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `modCrm` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `modEinvoice` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `modEway` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `modGst` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `modHrms` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `modInventory` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `modLoyalty` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `modMasters` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `modPharmacy` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `modPurchase` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `modReports` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `modSales` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `orgCentralInventory` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `orgCentralPricing` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `primaryDesignation` VARCHAR(100) NULL,
    ADD COLUMN `primaryEmail` VARCHAR(150) NULL,
    ADD COLUMN `primaryMobile` VARCHAR(30) NULL,
    ADD COLUMN `primaryName` VARCHAR(150) NULL,
    ADD COLUMN `sec2fa` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `secAudit` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `secOtp` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `secPwExpiry` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `secSession` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `secondaryDesignation` VARCHAR(100) NULL,
    ADD COLUMN `secondaryEmail` VARCHAR(150) NULL,
    ADD COLUMN `secondaryMobile` VARCHAR(30) NULL,
    ADD COLUMN `secondaryName` VARCHAR(150) NULL,
    ADD COLUMN `taxCgst` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `taxIgst` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `taxSgst` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `workFri` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `workMon` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `workSat` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `workSun` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `workThu` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `workTue` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `workWed` BOOLEAN NOT NULL DEFAULT false;
