-- Finance Cash Management: Fund Transfer (Cash <-> Bank) + Miscellaneous Receipt.
CREATE TABLE `cash_entries` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `tenantId` INTEGER NOT NULL,
  `businessId` INTEGER NULL,
  `branchId` INTEGER NULL,
  `kind` VARCHAR(20) NOT NULL,
  `docNo` VARCHAR(40) NOT NULL,
  `date` VARCHAR(20) NOT NULL,
  `transferType` VARCHAR(20) NULL,
  `fromAccount` VARCHAR(80) NULL,
  `toAccount` VARCHAR(80) NULL,
  `receivedIn` VARCHAR(10) NULL,
  `payer` VARCHAR(200) NULL,
  `incomeHead` VARCHAR(120) NULL,
  `mode` VARCHAR(20) NULL,
  `bankId` INTEGER NULL,
  `bankName` VARCHAR(120) NULL,
  `bankAccount` VARCHAR(60) NULL,
  `amount` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `reference` VARCHAR(120) NULL,
  `remarks` VARCHAR(300) NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'Posted',
  `journalRef` VARCHAR(40) NULL,
  `createdBy` INTEGER NULL,
  `createdByName` VARCHAR(200) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  INDEX `cash_entries_tenantId_branchId_date_idx`(`tenantId`, `branchId`, `date`),
  INDEX `cash_entries_tenantId_kind_idx`(`tenantId`, `kind`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
