CREATE TABLE `general_settings` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `tenantId` INTEGER NOT NULL,
  `baseCurrency` VARCHAR(10) NOT NULL DEFAULT 'INR',
  `currencySymbol` VARCHAR(6) NOT NULL DEFAULT '₹',
  `currencyPosition` VARCHAR(10) NOT NULL DEFAULT 'before',
  `numberSystem` VARCHAR(20) NOT NULL DEFAULT 'indian',
  `thousandSeparator` VARCHAR(20) NOT NULL DEFAULT 'indian',
  `amountDecimals` INTEGER NOT NULL DEFAULT 2,
  `qtyDecimals` INTEGER NOT NULL DEFAULT 2,
  `rateDecimals` INTEGER NOT NULL DEFAULT 2,
  `roundingMethod` VARCHAR(10) NOT NULL DEFAULT 'nearest',
  `roundingPrecision` VARCHAR(10) NOT NULL DEFAULT '1',
  `dateFormat` VARCHAR(20) NOT NULL DEFAULT 'dd-MMM-yyyy',
  `timeFormat` VARCHAR(5) NOT NULL DEFAULT '12h',
  `timezone` VARCHAR(40) NOT NULL DEFAULT 'Asia/Kolkata',
  `fiscalYearStart` VARCHAR(15) NOT NULL DEFAULT 'April',
  `weekStart` VARCHAR(15) NOT NULL DEFAULT 'Monday',
  `language` VARCHAR(10) NOT NULL DEFAULT 'en',
  `defaultPageSize` INTEGER NOT NULL DEFAULT 25,
  `sessionTimeout` INTEGER NOT NULL DEFAULT 30,
  `enableRounding` BOOLEAN NOT NULL DEFAULT true,
  `roundInPrint` BOOLEAN NOT NULL DEFAULT true,
  `showCurrencyCode` BOOLEAN NOT NULL DEFAULT false,
  `negativeInRed` BOOLEAN NOT NULL DEFAULT true,
  `autoLogout` BOOLEAN NOT NULL DEFAULT true,
  `confirmBeforeDelete` BOOLEAN NOT NULL DEFAULT true,
  `compactDensity` BOOLEAN NOT NULL DEFAULT false,
  `soundOnAction` BOOLEAN NOT NULL DEFAULT false,
  `rptShowReceipt` BOOLEAN NOT NULL DEFAULT true,
  `rptShowSales` BOOLEAN NOT NULL DEFAULT true,
  `rptShowReturn` BOOLEAN NOT NULL DEFAULT true,
  `rptShowDamage` BOOLEAN NOT NULL DEFAULT true,
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `general_settings_tenantId_key`(`tenantId`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `general_settings` ADD CONSTRAINT `general_settings_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `tenants`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
