-- CreateTable
CREATE TABLE `products` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `code` VARCHAR(60) NULL,
    `name` VARCHAR(250) NOT NULL,
    `shortName` VARCHAR(120) NULL,
    `altName` VARCHAR(120) NULL,
    `status` VARCHAR(20) NOT NULL DEFAULT 'Active',
    `launchDate` VARCHAR(20) NULL,
    `discontinuedDate` VARCHAR(20) NULL,
    `keywords` TEXT NULL,
    `description` TEXT NULL,
    `productType` VARCHAR(40) NULL,
    `category` VARCHAR(120) NULL,
    `subCategory` VARCHAR(120) NULL,
    `group` VARCHAR(120) NULL,
    `brand` VARCHAR(120) NULL,
    `manufacturer` VARCHAR(120) NULL,
    `family` VARCHAR(120) NULL,
    `segment` VARCHAR(120) NULL,
    `baseUom` VARCHAR(40) NULL,
    `purchaseUom` VARCHAR(40) NULL,
    `salesUom` VARCHAR(40) NULL,
    `packageType` VARCHAR(40) NULL,
    `unitsPerCase` INTEGER NULL,
    `weightUnit` VARCHAR(40) NULL,
    `netWeight` DECIMAL(18, 3) NULL,
    `grossWeight` DECIMAL(18, 3) NULL,
    `height` DECIMAL(18, 3) NULL,
    `width` DECIMAL(18, 3) NULL,
    `length` DECIMAL(18, 3) NULL,
    `volume` DECIMAL(18, 3) NULL,
    `sku` VARCHAR(60) NULL,
    `gtin` VARCHAR(60) NULL,
    `upc` VARCHAR(60) NULL,
    `ean` VARCHAR(60) NULL,
    `isbn` VARCHAR(60) NULL,
    `mpn` VARCHAR(60) NULL,
    `internalCode` VARCHAR(60) NULL,
    `barcodeType` VARCHAR(40) NULL,
    `barcodePrefix` VARCHAR(40) NULL,
    `barcodeLength` INTEGER NULL,
    `qrTemplate` VARCHAR(40) NULL,
    `taxPref` VARCHAR(30) NULL,
    `gstRate` VARCHAR(20) NULL,
    `hsn` VARCHAR(20) NULL,
    `sac` VARCHAR(20) NULL,
    `stdPurchasePrice` DECIMAL(18, 3) NULL,
    `lastPurchasePrice` DECIMAL(18, 3) NULL,
    `mrp` DECIMAL(18, 3) NULL,
    `retailPrice` DECIMAL(18, 3) NULL,
    `wholesalePrice` DECIMAL(18, 3) NULL,
    `distributorPrice` DECIMAL(18, 3) NULL,
    `dealerPrice` DECIMAL(18, 3) NULL,
    `franchisePrice` DECIMAL(18, 3) NULL,
    `onlinePrice` DECIMAL(18, 3) NULL,
    `localPrice` DECIMAL(18, 3) NULL,
    `interstatePrice` DECIMAL(18, 3) NULL,
    `salesRevenueAcct` VARCHAR(120) NULL,
    `salesInventoryAcct` VARCHAR(120) NULL,
    `purchaseExpenseAcct` VARCHAR(120) NULL,
    `purchaseInventoryAcct` VARCHAR(120) NULL,
    `costCenter` VARCHAR(120) NULL,
    `profitCenter` VARCHAR(120) NULL,
    `salesDesc` TEXT NULL,
    `purchaseDesc` TEXT NULL,
    `openingQty` DECIMAL(18, 3) NULL,
    `openingValue` DECIMAL(18, 3) NULL,
    `minStock` DECIMAL(18, 3) NULL,
    `maxStock` DECIMAL(18, 3) NULL,
    `reorderLevel` DECIMAL(18, 3) NULL,
    `safetyStock` DECIMAL(18, 3) NULL,
    `leadTime` INTEGER NULL,
    `shelfLifeType` VARCHAR(20) NULL,
    `shelfLifeValue` INTEGER NULL,
    `alertUnit` VARCHAR(20) NULL,
    `alertValue` INTEGER NULL,
    `preferredSupplier` VARCHAR(150) NULL,
    `purchaseLeadTime` INTEGER NULL,
    `invStockMaintenance` BOOLEAN NOT NULL DEFAULT false,
    `invBatch` BOOLEAN NOT NULL DEFAULT false,
    `invLot` BOOLEAN NOT NULL DEFAULT false,
    `invSerial` BOOLEAN NOT NULL DEFAULT false,
    `invMfg` BOOLEAN NOT NULL DEFAULT false,
    `invExpiry` BOOLEAN NOT NULL DEFAULT false,
    `invWarranty` BOOLEAN NOT NULL DEFAULT false,
    `invTrace` BOOLEAN NOT NULL DEFAULT false,
    `ctrlNegative` BOOLEAN NOT NULL DEFAULT false,
    `ctrlBackorder` BOOLEAN NOT NULL DEFAULT false,
    `ctrlReservation` BOOLEAN NOT NULL DEFAULT false,
    `ctrlBlocking` BOOLEAN NOT NULL DEFAULT false,
    `salesAllowed` BOOLEAN NOT NULL DEFAULT false,
    `salesReturnAllowed` BOOLEAN NOT NULL DEFAULT false,
    `bulkSales` BOOLEAN NOT NULL DEFAULT false,
    `creditSales` BOOLEAN NOT NULL DEFAULT false,
    `discountAllowed` BOOLEAN NOT NULL DEFAULT false,
    `ageRestricted` BOOLEAN NOT NULL DEFAULT false,
    `specialApproval` BOOLEAN NOT NULL DEFAULT false,
    `rxPrescription` BOOLEAN NOT NULL DEFAULT false,
    `rxSchedule` BOOLEAN NOT NULL DEFAULT false,
    `rxBatchMandatory` BOOLEAN NOT NULL DEFAULT false,
    `rxExpiryMandatory` BOOLEAN NOT NULL DEFAULT false,
    `rxDrugLicense` BOOLEAN NOT NULL DEFAULT false,
    `autoBarcode` BOOLEAN NOT NULL DEFAULT false,
    `qrRequired` BOOLEAN NOT NULL DEFAULT false,
    `expiryApplicable` BOOLEAN NOT NULL DEFAULT false,
    `purchaseAllowed` BOOLEAN NOT NULL DEFAULT false,
    `maxDiscountEnabled` BOOLEAN NOT NULL DEFAULT false,
    `approvalStatus` VARCHAR(20) NOT NULL DEFAULT 'draft',
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `products_code_key`(`code`),
    INDEX `products_name_idx`(`name`),
    INDEX `products_category_idx`(`category`),
    INDEX `products_brand_idx`(`brand`),
    INDEX `products_status_idx`(`status`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `product_attributes` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `productId` INTEGER NOT NULL,
    `name` VARCHAR(120) NULL,
    `type` VARCHAR(40) NULL,
    `values` VARCHAR(500) NULL,

    INDEX `product_attributes_productId_idx`(`productId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `product_attributes` ADD CONSTRAINT `product_attributes_productId_fkey` FOREIGN KEY (`productId`) REFERENCES `products`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
