-- Supplier Master: extend the suppliers table + addresses sub-table.

ALTER TABLE `suppliers`
  ADD COLUMN `code` VARCHAR(40) NULL,
  ADD COLUMN `legalName` VARCHAR(200) NULL,
  ADD COLUMN `type` VARCHAR(40) NULL,
  ADD COLUMN `website` VARCHAR(200) NULL,
  ADD COLUMN `description` VARCHAR(500) NULL,
  ADD COLUMN `contact1Designation` VARCHAR(80) NULL,
  ADD COLUMN `altMobile` VARCHAR(30) NULL,
  ADD COLUMN `contact2Name` VARCHAR(120) NULL,
  ADD COLUMN `contact2Designation` VARCHAR(80) NULL,
  ADD COLUMN `contact2Mobile` VARCHAR(30) NULL,
  ADD COLUMN `contact2Email` VARCHAR(150) NULL,
  ADD COLUMN `pan` VARCHAR(20) NULL,
  ADD COLUMN `tan` VARCHAR(20) NULL,
  ADD COLUMN `stateCode` VARCHAR(10) NULL,
  ADD COLUMN `placeOfSupply` VARCHAR(80) NULL,
  ADD COLUMN `tdsPct` DECIMAL(9, 2) NOT NULL DEFAULT 0,
  ADD COLUMN `bankName` VARCHAR(120) NULL,
  ADD COLUMN `bankBranch` VARCHAR(120) NULL,
  ADD COLUMN `accountHolder` VARCHAR(200) NULL,
  ADD COLUMN `accountNumber` VARCHAR(40) NULL,
  ADD COLUMN `ifsc` VARCHAR(20) NULL,
  ADD COLUMN `accountType` VARCHAR(20) NULL,
  ADD COLUMN `upi` VARCHAR(80) NULL,
  ADD COLUMN `creditAllowed` BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN `creditLimit` DECIMAL(18, 2) NOT NULL DEFAULT 0,
  ADD COLUMN `creditPeriod` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `ledgerAccount` VARCHAR(120) NULL,
  ADD COLUMN `advanceAccount` VARCHAR(120) NULL,
  ADD COLUMN `purchaseAccount` VARCHAR(120) NULL,
  ADD COLUMN `openingPayable` DECIMAL(18, 2) NOT NULL DEFAULT 0,
  ADD COLUMN `openingAdvance` DECIMAL(18, 2) NOT NULL DEFAULT 0,
  ADD COLUMN `preferred` BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN `approvalStatus` VARCHAR(20) NOT NULL DEFAULT 'draft',
  ADD COLUMN `notes` VARCHAR(1000) NULL;

CREATE TABLE `supplier_addresses` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `tenantId` INTEGER NOT NULL,
  `supplierId` INTEGER NOT NULL,
  `label` VARCHAR(20) NOT NULL DEFAULT 'Other',
  `line1` VARCHAR(200) NULL,
  `line2` VARCHAR(200) NULL,
  `city` VARCHAR(80) NULL,
  `district` VARCHAR(80) NULL,
  `state` VARCHAR(80) NULL,
  `country` VARCHAR(80) NULL,
  `pincode` VARCHAR(12) NULL,
  `isDefault` BOOLEAN NOT NULL DEFAULT false,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX `supplier_addresses_supplierId_idx`(`supplierId`),
  PRIMARY KEY (`id`),
  CONSTRAINT `supplier_addresses_supplierId_fkey` FOREIGN KEY (`supplierId`) REFERENCES `suppliers`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
